sudo: required
services:
  -docker
before-install:
  - docker build -t brendachirata/reactfrontend -f Dockerfile.dev .
script:
  - docker run -e CI=true brendachirata/reactfrontend npm run test -- --coverage 